### ISSUE TITLE
Incorrect function overloading

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/luabind-deboostified#10]
If you have function with default arguments, like this:
```cpp
void Kill(CScriptGameObject* who, bool bypass_actor_check = false);
```
It would be exported to Lua as a functions that accepts two arguments, but not one. If you will try to call it with one argument it will crash.

In the previous luabind version you could use casts to fix the problem:
```cpp
.def("kill", (void (CScriptGameObject::*)(CScriptGameObject*))&CScriptGameObject::Kill)
.def("kill", (void (CScriptGameObject::*)(CScriptGameObject*, bool))(&CScriptGameObject::Kill))
```

In this new version this doesn't help. The second parameter will be filled with trash.

**Comment by Xottab-DUTY** [comment]
#13 is definitely related to this issue. But I don't remember if it fully fixes it or there are problems remain. Sorry, @qweasdd136963 can you remind me?

**Comment by qweasdd136963** [comment]
частично исправил. Теперь если при вызове не указывать  аргумент по умолчанию, вылета не будет. но вместо этого вместо него будут посланы нуль или false.

**Comment by Xottab-DUTY** [comment]
Fixable only with constructions like this:
```cpp
.def("kill", &CScriptGameObject::Kill) // lua:kill(who, true)
.def("kill", +[](CScriptGameObject* thisPtr, CScriptGameObject* who) { thisPtr->Kill(who); }) // lua:kill(who)
```
