### ISSUE TITLE
Permissive mode

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/luabind-deboostified#11]
The previous version of luabind was very permissive for script errors.
For example, you have a function and it is exported to Lua:
```cpp
void func(int arg1, int arg2); // functions itself

.def("func", &func) // export
```
If you pass to this functions wrong parameters, like this:
```lua
func("__") -- Passing string instead of a number. This is wrong!!!
		   -- The second argument is forgotten. This is wrong too!!!
```
Nothing will happen. The script just hang and that's all. No crash will proceed.

But in this new version it crashes on every error and doesn't have a permissive mode, which is bad for compatibility.

We should add some sort of permissive mode that ignores the errors like it was before.

**Comment by qweasdd136963** [comment]
пофикшено  https://github.com/OpenXRay/luabind-deboostified/commit/5064ded13c8173df90ef016eb1fd4794e7906872

**Comment by qweasdd136963** [comment]
но на миксед, дебаге все равно будет вылетать, так захотел хоттаб

**Comment by Xottab-DUTY** [comment]
Да, правильно. Спасибо.
