### ISSUE TITLE
How to deal with missing allocator?

### ISSUE THREAD

**Issue by Wohlstand** [OpenXRay/luabind-deboostified#15]
I have tried to use this in my project, and I have found the extern `alloc_func allocator` which is missing... (my program is crashing on an attempt to load of LuaBind and fails on allocator as "calling pure-virtual method"). Where I can take the proper allocator and it's context to make this thing working?

https://github.com/OpenXRay/luabind-deboostified/blob/xray/src/memory.cpp

**Comment by Wohlstand** [comment]
Okay, should I probably revert this on my side? https://github.com/OpenXRay/luabind-deboostified/commit/7327ea55e2446a2be312dbd776c568834c2be020#diff-7ccb8208baae9fa8664990a4f55d1b9e

**Comment by Xottab-DUTY** [comment]
You can either revert it or look at our standard allocator here: https://github.com/OpenXRay/xray-16/blob/xd_dev/src/xrScriptEngine/script_engine.cpp#L57

And we set it up like this:
```cpp
CScriptEngine::CScriptEngine(bool is_editor)
{
    luabind::allocator = &luabind_allocator;
    luabind::allocator_context = nullptr;
	... // other code
}
```

**Comment by Wohlstand** [comment]
Thanks, looks like I should try to apply this allocator... Thanks for the hint! :fox_face:

**Comment by Wohlstand** [comment]
Okay, so, it works now, however, the next my challenge is `luabind::string` - a `std::string` with custom allocator set, where I should deal with compatibility between `std::string` and `luabind::string`... This is another challenge, and the question of the allocator is finally solved.
